### ISSUE TITLE
Installation fails with no link.config file

### ISSUE THREAD

**Issue by drewbo** [SpringServe/springserve-python#5]
`pip install springserve` fails with
```
link.exceptions.LNKConfigException: Error parsing config
problem loading link, this is ok on the install
```
(pip version 7.1.2)
However, the text saying it is okay doesn't prevent it from having exit code 1 so the installation fails. As a workaround, I created an empty JSON file at `~/.link/link.config` and the installation succeeds. 

This works for OSX users but will fail on Windows because the `~` expansion is hardcoded in the underlying `link` library (and providing an alternative path with `LNK_DIR` during installation didn't seem to have any effect)

**Comment by dhrod5** [comment]
I believe this is no longer an issue.  Sorry I did not see this.
